### ISSUE TITLE
Chromecast dashboard stops working in last version of Google Chrome

### ISSUE THREAD

**Issue by nkuznetsow** [boombatower/chromecast-dashboard#11]
I have chrome v. 71.0.3578.98 (64 bit) running on windows 7 SP 1. Since update to this Google Chrome version Chromecast dashboard stops working. 

Chromecast-dashboard is the best tool for displaying dashboards on TV so, please fix it. I suppose you need not much time but you can make me and other people happy!

**Comment by boombatower** [comment]
I cannot verify this running `Version 71.0.3578.98 (Official Build) (64-bit)` on `Linux` as it works fine.

I did remove an out-dated check for receivers since the API was changed to were this is no longe relevant. Perhaps you are seeing this error message and not attempting to cast? Otherwise, I would check your firewall and network settings.

40c7d2619b04744a63d98e7b1f731c5d9def9cd9

**Comment by boombatower** [comment]
Re-open if still a problem with more details to aid in reproducing the issue.
