### ISSUE TITLE
Cast static html from NodeJS App

### ISSUE THREAD

**Issue by raftheunis87** [boombatower/chromecast-dashboard#13]
Hey man,

First of all, thanks for this repo! It made a few things about this cast receiver clear for me ;-).

I was wondering if it would be possible to trigger something on a chromecast from a nodejs application? Like when you would trigger a REST endpoint for example, that the result would not only be a JSON response, but also that something is casted on a screen? By something I mean a static HTML site with some styling or something like that?

**Comment by boombatower** [comment]
If you can run the sender app in such a way that you can communicate with it and send it commands from your REST endpoint you could then trigger whatever you want on the chromecast (ex. URL change, or send custom event to custom receiver). The tricky bit is that since the chromecast 1.x API was abandoned you have to communicate through a Google provided chromecast API (like android, ios, or chome).

**Comment by IamMille** [comment]
> since the chromecast 1.x API was abandoned
@boombatower  does that mean that cloning this repo and setting up a new application in the Cast SDK Developer Console wont work? Cause I've just forked this repo to try and set it up myself, without success.
