### ISSUE TITLE
1080 resolution

### ISSUE THREAD

**Issue by stellanhaglund** [boombatower/chromecast-dashboard#4]
Hi, I have tried your application and it works good, but I can't figure out how to cast in 1920x1080, I have tried using the chrome cast beta plugin which allows me to set that resolution but it's not working.

**Comment by boombatower** [comment]
Chromecast only supports 720p for receiver apps (ie non-media playback). I could not find the reference I remember, but https://developers.google.com/cast/docs/android_tv#compat also indicates 720p:

> While Chromecast displays the receiver page on a 720p graphics plane, other Cast platforms including Android TV may display the page up to 1080p. Ensure your receiver page scales gracefully at different resolutions.

The resolution setting in the extension is used when tab streaming, not when running custom receiver apps (like the chromecast-dashboard). My understanding is the 720p limitation is due to chip being optimized for media decoding and not general page rendering (ie animations and such can be choppy even at 720p).
