### ISSUE TITLE
Is it possible to provide login-information?

### ISSUE THREAD

**Issue by PatrickHuetter** [boombatower/chromecast-dashboard#6]
I would like to use chromecast-dashboard to render some graylog-dashboards to some of my monitoring screens. At this time i'm using raspberry pis but they are too slow in website rendering because of missing x11 acceleration.

Is it possible to do a login with chromecast-dashboard? If it's not possible by creating a post request, is it possible to authenticate by http basic auth? This would be a very nice feature!

PS. I know that i could copy a valid session id into the graylog-dashboard url, but i think that's not the preferred way to do this.

Best regards

**Comment by boombatower** [comment]
Since the dashboard just uses a fullscreen iframe it does not control sending headers or such as may be possible with javascript http request calls. Based on stack overflow it appears you can include the authentication information in the url.

```
<iframe src="http://username:password@domain.tld/..."></iframe>
```

http://stackoverflow.com/questions/11439927/how-can-i-http-authentication-login-with-javascript-for-an-iframe

Try passing that in as part of the URL on the sender.

The benefit of using an iframe is that it gets around xhr header issues and thus allows displaying any page that does not block loading in an iframe.

**Comment by PatrickHuetter** [comment]
Ok thanks, i'll look further.
Am 12.03.2016 6:15 vorm. schrieb "Jimmy Berry" notifications@github.com:

**Comment by boombatower** [comment]
Please reopen if further action and please add a note if it works out. :)
